# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

parameters:
  - name: appCenterServiceConnection
    displayName: 'App Center Integration for Sample App'
  - name: appSlug
    displayName: 'Vishal.Kharat_Extentia/AzureDevOps'
  - name: appFile
    displayName: '**/*.apk'
  - name: releaseNotes
    displayName: 'Release notes'


steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'


- task: AppCenterDistribute@3
  inputs:
      serverEndpoint: '${{ parameters.appCenterServiceConnection }}'
      appSlug: '${{ parameters.appSlug }}'
      appFile: '${{parameters.appFile}}'
      symbolsOption: 'Android'
      destinationType: 'groups'
      releaseNotesOption: 'input'
      releaseNotesInput: '${{parameters.releaseNotes}}'
  displayName: 'Distribute to App Center'